import { useState, type FormEvent } from 'react'
import type { Product } from '../../types/product'
import type { AuthUser } from '../../types/auth'
import { inventoryService } from '../../services'
import { Modal } from '../ui/Modal'
export function ProductEditModal({product,actor,onClose}:{product:Omit<Product,'costPrice'>&{costPrice?:number};actor:AuthUser;onClose:()=>void}) {
  const [name,setName]=useState(product.name),[price,setPrice]=useState(String(product.sellingPrice)),[cost,setCost]=useState(String(product.costPrice??0)),[threshold,setThreshold]=useState(String(product.lowStockThreshold)),[available,setAvailable]=useState(product.isAvailable),[archived,setArchived]=useState(product.isArchived),[error,setError]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();try{await inventoryService.updateProduct(product.id,{name,sellingPrice:Number(price),costPrice:Number(cost),lowStockThreshold:Number(threshold),isAvailable:available,isArchived:archived},actor);onClose()}catch(e){setError(e instanceof Error?e.message:'Update failed.')}}
  return <Modal title="Edit product" onClose={onClose}><form className="operation-form" onSubmit={submit}><label className="field">Product name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Selling price (₱)<input required type="number" min="0" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="field">Cost price (Owner only)<input required type="number" min="0" step=".01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label className="field">Low-stock threshold<input required type="number" min="0" step="1" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><label className="checkbox-field"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/>Available for sale</label><label className="checkbox-field"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Archived (hidden from catalog and POS)</label><p className="muted">SKU and barcode: {product.sku} / {product.barcode}</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-primary">Save product</button></form></Modal>
}
